services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: talentwright_frontend:latest
    container_name: talentwright_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://django:8000
    networks:
      - default

networks:
  default:
    name: talentwright_default
    external: true
